### ISSUE TITLE
Sam badge for Abubakar

### ISSUE THREAD

**Issue by Samuelbly** [AbubakarBunamay/moraveil#68]
Issue Title: Badge For Abubakar

Issue Description:
everyone else ignore issue

Severity:
meme

Room/Environment:
N/A
Version:
none

Reproduction Steps:
haha funnies
...

Expected Behavior:
make a meme :)

Actual Behavior:
meme

Screenshots/Attachments:
N/A

Additional Information:
N/A
Assigned To:
N/A

Labels:
N/A

image
N/A
Comments:
N/A

**Comment by AbubakarBunamay** [comment]
Thanks
